/*Enzo Rafael*/
CREATE DATABASE BDCADASTRO

USE BDCADASTRO

CREATE TABLE CLIENTE
( 
IDCLIENTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOME NVARCHAR(50) NOT NULL,
IDADE INT NOT NULL,
TELEFONE NVARCHAR(15),
ENDEREÇO NVARCHAR(100),
EMAIL NVARCHAR (50)
 ) 
 
INSERT INTO CLIENTE (NOME,IDADE,TELEFONE,ENDEREÇO,EMAIL)
VALUES
('PEDRO PEDRA',26,'(11)666-999','RUA ARMARINHO FONSECA,666','robloxo@gmail.com')


INSERT INTO CLIENTE VALUES 
('JOAO FREITAS', 46, '(11)777-666','RUA VIRGINIA FERNI,777','jaofreiras@gmail.com')

UPDATE CLIENTE SET TELEFONE = '(15)9799-8989'
WHERE IDCLIENTE = 2

INSERT INTO CLIENTE VALUES
('ANDRÉ',16,'(11)2122-1212','RUA DOS BUCANEIROS,999','andreramiro@gmail.com'),
('ANDRÉ',16,'(15)2222-1313','RUA DOS POLITICOS,555','andresch@gmail.com')

UPDATE CLIENTE SET IDADE = 30
WHERE NOME = 'ANDRÉ'

DELETE FROM CLIENTE
WHERE IDCLIENTE = 4